# Use an official Python image as the base
FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Set PYTHONUNBUFFERED to 1 to ensure output is displayed immediately
ENV PYTHONUNBUFFERED=1

RUN apt-get update \
    && apt-get -y install libpq-dev gcc

# Copy the requirements file
COPY requirements*.txt .

# Install dependencies
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .

# Run the application
ENTRYPOINT ["fastapi", "dev", "src/main.py", "--port", "8000", "--host", "0.0.0.0"]
